export default [
  {
    id: 1,
    lat: 0,
    lng: 0,
    name: "Planejamento Estratégico e Inovação - Básico",
    description: "Planeje o seu Sucesso de forma Rápida e Intuitiva",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "QUA, 10 NOV - 17:00",
    categoryId: 1,
    imageUrl: "banner-gradient.jpg",
    cityId: 1,
  },
  {
    id: 2,
    lat: 0,
    lng: 0,
    name: "Curso Marketing para Eventos",
    description: "Planejando o sold out com RD & Sympla",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "QUA, 10 NOV - 17:00",
    categoryId: 1,
    imageUrl: "banner-gradient.jpg",
    cityId: 2,
  },
  {
    id: 3,
    lat: 0,
    lng: 0,
    name: "Curso Completo de Mídia Programática",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "QUA, 10 NOV - 17:00",
    categoryId: 1,
    imageUrl: "banner-gradient.jpg",
    cityId: 3,
  },
  {
    id: 4,
    lat: 0,
    lng: 0,
    name: "Criando um Planejamento",
    description: "APRENDE A CRIAR PLANEJAMENTO E A AXECUTAR",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SÁB, 13 DEZ - 18:00",
    categoryId: 2,
    imageUrl: "banner-gradient.jpg",
    cityId: 4,
  },
  {
    id: 5,
    lat: 0,
    lng: 0,
    name: "Curso de comportamento do consumidor",
    description: "Curso completo e gratuito",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "QUA, 10 NOV - 17:00",
    categoryId: 2,
    imageUrl: "banner-gradient.jpg",
    cityId: 5,
  },
  {
    id: 6,
    lat: 0,
    lng: 0,
    name: "Abordagens de Vendas em Tempos de Pandemia",
    description: "Melhore sua capacidade de abordagem a clientes",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "QUA, 10 NOV - 17:00",
    categoryId: 2,
    imageUrl: "banner-gradient.jpg",
    cityId: 6,
  },
  {
    id: 8,
    lat: 0,
    lng: 0,
    name: "Einstein Frontiers: Inovação, Saúde Digital, Tecnologia Médica e Ciência de Dados",
    description: "Some Description",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "QUA, 17 NOV - 09:00",
    categoryId: 3,
    imageUrl: "banner-gradient.jpg",
    cityId: 7,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 3,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Formação de Consultores de Logística e Supply Chain.",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "TER, 21 DEZ - 22:00",
    categoryId: 3,
    imageUrl: "banner-gradient.jpg",
    cityId: 9,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 4,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 4,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 4,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 5,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 5,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 5,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 6,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 6,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 6,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 7,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 7,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 7,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 8,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 8,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
  {
    id: 7,
    lat: 0,
    lng: 0,
    name: "Logística Empresarial: Operação e Estratégia",
    description: "",
    address: "Santa Helena, 370, Picos, Piauí, Brasil",
    eventDate: "SEX, 17 DEZ - 19:00",
    categoryId: 8,
    imageUrl: "banner-gradient.jpg",
    cityId: 8,
  },
];
